module.exports = {
	COMMUNITY_CHAT:'COMMUNITY_CHAT',
	USER_CONNECTED:'USER_CONNECTED',
	MESSAGE_RECIEVED:'MESSAGE_RECIEVED',
	MESSAGE_SENT:'MESSAGE_SENT',
	USER_DISCONNECTED:'USER_DISCONNECTED',
	TYPING:'TYPING',
	VERYFY_USER:'VERYFY_USER',
	LOGOUT:'LOGOUT',
}
