export default {
	COMMUNITY_CHAT : 'COMMUNITY_CHAT',
	USER_CONNECTED : 'USER_CONNECTED',
	MESSAGE_RECIEVED : 'MESSAGE_RECIEVED',
	MESSAGE_SENT : 'MESSAGE_SENT',
	USER_DISCONNECTED : 'USER_DISCONNECTED',
	TYPING : 'TYPING',
	VERiFY_USER : 'VERiFY_USER',
	LOGOUT : 'LOGOUT',
};
