language: node_js
node_js:
  - "8"
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run client-build
script:
  - nohup npm run start &
  - sleep 4
#  - npm run test
